// SPDX-License-Identifier: GPL-3.0-only
/* Generated by tools/generate_303_wavetables.py. Do not hand-edit. */
#ifndef REFM_ACID303_WAVETABLE_H
#define REFM_ACID303_WAVETABLE_H
#include <stdint.h>
#define REFM_ACID_WT_BANDS 10u
#define REFM_ACID_WT_SIZE 512u
#define REFM_ACID_WT_MASK 511u
static const uint32_t refm_acid_wt_threshold_inc[REFM_ACID_WT_BANDS-1u] = {
    4012867u, 6370030u, 10111792u, 16053567u, 25484510u, 40447168u, 64201046u, 101904350u, 161759044u
};
static const uint16_t refm_acid_wt_harmonics[REFM_ACID_WT_BANDS] = {
    674, 424, 267, 168, 106, 66, 42, 26, 16, 10
};
