// SPDX-License-Identifier: GPL-3.0-only
#include "drum_machine.h"
#include <string.h>
static int16_t clip16(int32_t v){return(int16_t)(v<-32768?-32768:v>32767?32767:v);}static int32_t tri(uint32_t p){uint32_t q=p>>16;return q<32768u?(int32_t)q*2-32768:98302-(int32_t)q*2;}static int32_t sq(uint32_t p){return(p&0x80000000u)?-32768:32767;}static int32_t nz(drum_machine_t*d){uint32_t x=d->noise?d->noise:0x12345678u;x^=x<<13;x^=x>>17;x^=x<<5;d->noise=x;return(int32_t)(x>>16)-32768;}
static void setup(drum_machine_t*d,drum_voice_id_t id,uint8_t vel){static const uint32_t inc[DRUM_VOICES]={38000000u,72000000u,0u,120000000u,210000000u,190000000u,52000000u,61000000u,70000000u,150000000u,125000000u};static const uint8_t dec[DRUM_VOICES]={10u,9u,8u,9u,7u,10u,10u,10u,10u,9u,11u};drum_voice_state_t*v=&d->voice[id];memset(v,0,sizeof(*v));uint32_t boost=d->model==DRUM_MODEL_909?108u:100u;v->inc1=(inc[id]/100u)*boost;v->inc2=v->inc1+((id==DRUM_CH||id==DRUM_OH||id==DRUM_CR||id==DRUM_RD)?53000000u:17000000u);v->env=(int32_t)vel*258;v->tone=v->env;v->decay_shift=dec[id];v->active=1u;}
void drum_machine_clear_samples(drum_machine_t*d){d->sample_mask=0u;d->sample_use_mask=0u;for(unsigned i=0;i<DRUM_VOICES;i++){d->sample_pcm[i]=0;d->sample_frames[i]=0u;d->sample_rate[i]=44100u;sample_voice_init(&d->sample_voice[i]);}}
void drum_machine_set_sample(drum_machine_t*d,drum_voice_id_t id,const int16_t*pcm,uint32_t frames,uint32_t rate){if((unsigned)id>=DRUM_VOICES)return;d->sample_pcm[id]=pcm;d->sample_frames[id]=frames;d->sample_rate[id]=rate?rate:44100u;if(pcm&&frames){d->sample_mask|=(uint16_t)(1u<<id);d->sample_use_mask|=(uint16_t)(1u<<id);}else{d->sample_mask&=(uint16_t)~(1u<<id);d->sample_use_mask&=(uint16_t)~(1u<<id);}sample_voice_init(&d->sample_voice[id]);}
void drum_machine_enable_samples(drum_machine_t*d,uint8_t enabled){d->samples_enabled=enabled?1u:0u;}
void drum_machine_set_sample_lane(drum_machine_t*d,drum_voice_id_t id,uint8_t enabled){if((unsigned)id>=DRUM_VOICES)return;if(enabled)d->sample_use_mask|=(uint16_t)(1u<<id);else d->sample_use_mask&=(uint16_t)~(1u<<id);}
void drum_machine_set_sample_use_mask(drum_machine_t*d,uint16_t mask){d->sample_use_mask=mask&(uint16_t)((1u<<DRUM_VOICES)-1u);}
uint16_t drum_machine_sample_active_mask(const drum_machine_t*d){return d->samples_enabled?(uint16_t)(d->sample_use_mask&d->sample_mask):0u;}
uint8_t drum_machine_sample_available(const drum_machine_t*d,drum_voice_id_t id){if((unsigned)id>=DRUM_VOICES)return 0u;return(d->sample_mask&(uint16_t)(1u<<id))?1u:0u;}
void drum_machine_init(drum_machine_t*d,drum_model_t model){memset(d,0,sizeof(*d));d->model=model;d->noise=0x13579bdfu;d->samples_enabled=0u;drum_machine_clear_samples(d);}void drum_machine_trigger(drum_machine_t*d,drum_voice_id_t id,uint8_t vel){uint32_t step;uint16_t bit;if((unsigned)id>=DRUM_VOICES)return;if(!vel)vel=1u;if(id==DRUM_CH){d->voice[DRUM_OH].env>>=3;d->sample_voice[DRUM_OH].active=0u;}bit=(uint16_t)(1u<<id);if(d->samples_enabled&&(d->sample_use_mask&bit)&&drum_machine_sample_available(d,id)){step=(uint32_t)(((uint64_t)d->sample_rate[id]<<16)/44100u);sample_voice_trigger_rate(&d->sample_voice[id],d->sample_pcm[id],d->sample_frames[id],vel,step);d->voice[id].active=0u;}else setup(d,id,vel);}
static int32_t render(drum_machine_t*d,drum_voice_id_t id){drum_voice_state_t*v=&d->voice[id];if(!v->active||v->env<=0)return 0;v->phase1+=v->inc1;v->phase2+=v->inc2;int32_t e=v->env,y=0;switch(id){case DRUM_BD:v->phase1+=(uint32_t)e<<9;y=(tri(v->phase1)*e)>>15;break;case DRUM_SD:y=((tri(v->phase1)*e)>>16)+((nz(d)*(e*3/4))>>15);break;case DRUM_CP:{uint32_t g=(uint32_t)e>>11;int32_t n=nz(d);y=((g&3u)==0u?n:n/3);y=(y*e)>>15;break;}case DRUM_RS:y=((sq(v->phase1)+sq(v->phase2))*e)>>16;break;case DRUM_CH:case DRUM_OH:y=((sq(v->phase1)^sq(v->phase2))*e)>>15;y=(y+((nz(d)*e)>>16))/2;break;case DRUM_LT:case DRUM_MT:case DRUM_HT:y=(tri(v->phase1)*e)>>15;break;case DRUM_CR:case DRUM_RD:y=((sq(v->phase1)+sq(v->phase2)+nz(d))*e)>>17;break;default:break;}int32_t dd=e>>v->decay_shift;if(dd<1)dd=1;v->env-=dd;if(v->env<48){v->env=0;v->active=0u;}return y;}
int16_t drum_machine_process(drum_machine_t*d){int32_t s=0;for(unsigned i=0;i<DRUM_VOICES;i++){s+=render(d,(drum_voice_id_t)i);s+=sample_voice_process(&d->sample_voice[i]);}if(d->model==DRUM_MODEL_909)s=(s*11)/10;return clip16(s);}
