// SPDX-License-Identifier: GPL-3.0-only
#include "groovebox.h"
#include <string.h>

static int16_t acid_sample(acid303_t*s){int32_t v=acid303_process(s);if(v<-32768)v=-32768;if(v>32767)v=32767;return(int16_t)v;}
static void active_to_bank(pattern_bank_t*b,const groovebox_t*g,uint8_t p){if(p>=PATTERN_BANK_COUNT)return;for(unsigned a=0;a<2u;a++)memcpy(b->acid[a][p],g->acid_seq[a].step,sizeof(b->acid[a][p]));for(unsigned d=0;d<2u;d++){memcpy(b->drum_hits[d][p],g->drum_hits[d],sizeof(b->drum_hits[d][p]));memcpy(b->drum_accents[d][p],g->drum_accents[d],sizeof(b->drum_accents[d][p]));}}
static void bank_to_active(const pattern_bank_t*b,groovebox_t*g,uint8_t p){if(p>=PATTERN_BANK_COUNT)return;for(unsigned a=0;a<2u;a++){memcpy(g->acid_seq[a].step,b->acid[a][p],sizeof(b->acid[a][p]));seq16_reset(&g->acid_seq[a]);}for(unsigned d=0;d<2u;d++){memcpy(g->drum_hits[d],b->drum_hits[d][p],sizeof(b->drum_hits[d][p]));memcpy(g->drum_accents[d],b->drum_accents[d][p],sizeof(b->drum_accents[d][p]));}g->current_pattern=p;g->step=0u;}

void groovebox_init(groovebox_t*g,uint16_t bpm){memset(g,0,sizeof(*g));for(unsigned i=0;i<2u;i++){acid303_init(&g->acid[i]);seq16_init(&g->acid_seq[i],0x1001u+i*0x1111u);}drum_machine_init(&g->drum[0],DRUM_MODEL_808);drum_machine_init(&g->drum[1],DRUM_MODEL_909);pattern_bank_init(&g->patterns);mixer_fx_init(&g->mixer);midi_transport_init(&g->transport,bpm);song_init(&g->song);}
void groovebox_set_external_clock(groovebox_t*g,uint8_t e){g->external_clock=e?1u:0u;}
void groovebox_set_drum_step(groovebox_t*g,uint8_t d,uint8_t s,uint16_t h,uint16_t a){if(d>=2u||s>=16u)return;uint16_t m=(uint16_t)((1u<<DRUM_VOICES)-1u);g->drum_hits[d][s]=h&m;g->drum_accents[d][s]=a&m;}
void groovebox_advance_step(groovebox_t*g){for(unsigned t=0;t<2u;t++){seq16_event_t e=seq16_advance(&g->acid_seq[t]);if(!e.valid)acid303_note_off(&g->acid[t]);else if(e.note_on)acid303_set_note(&g->acid[t],e.note,e.accent,e.slide);}for(unsigned d=0;d<2u;d++){uint16_t h=g->drum_hits[d][g->step],a=g->drum_accents[d][g->step];for(unsigned v=0;v<DRUM_VOICES;v++)if(h&(1u<<v))drum_machine_trigger(&g->drum[d],(drum_voice_id_t)v,(a&(1u<<v))?127u:96u);}g->step=(uint8_t)((g->step+1u)&15u);if(g->step==0u&&g->song.length){song_event_t e=song_advance(&g->song);if(e.valid&&e.pattern<PATTERN_BANK_COUNT&&e.pattern!=g->current_pattern){active_to_bank(&g->patterns,g,g->current_pattern);bank_to_active(&g->patterns,g,e.pattern);}}}
uint32_t groovebox_feed_midi_realtime(groovebox_t*g,uint8_t status){uint32_t e=midi_transport_feed_realtime(&g->transport,status);if(e&MT_EVT_START){g->step=0u;for(unsigned i=0;i<2u;i++)seq16_reset(&g->acid_seq[i]);song_reset(&g->song);}if((e&MT_EVT_STEP)&&g->external_clock)groovebox_advance_step(g);return e;}
void groovebox_process(groovebox_t*g,int16_t*l,int16_t*r){if(!g->external_clock){uint32_t e=midi_transport_process_samples(&g->transport,1u);if(e&MT_EVT_STEP)groovebox_advance_step(g);}int16_t in[MIX_TRACKS]={acid_sample(&g->acid[0]),acid_sample(&g->acid[1]),drum_machine_process(&g->drum[0]),drum_machine_process(&g->drum[1])};mixer_fx_process(&g->mixer,in,l,r);}

static void p8(uint8_t**p,uint8_t v){*(*p)++=v;}static void p16(uint8_t**p,uint16_t v){p8(p,(uint8_t)v);p8(p,(uint8_t)(v>>8));}static void p32(uint8_t**p,uint32_t v){p16(p,(uint16_t)v);p16(p,(uint16_t)(v>>16));}static uint8_t g8(const uint8_t**p){return*(*p)++;}static uint16_t g16(const uint8_t**p){uint16_t a=g8(p),b=g8(p);return a|(uint16_t)(b<<8);}static uint32_t g32(const uint8_t**p){uint32_t a=g16(p),b=g16(p);return a|(b<<16);}

int groovebox_save(const groovebox_t*g,uint8_t*out,size_t cap,size_t*written){uint8_t b[GROOVEBOX_PROJECT_PAYLOAD_MAX],*p=b;p16(&p,g->transport.bpm);p8(&p,g->current_pattern);p8(&p,g->external_clock);for(unsigned a=0;a<2u;a++){const acid303_t*s=&g->acid[a];p16(&p,s->cutoff);p16(&p,s->resonance);p16(&p,s->env_mod);p16(&p,s->decay);p16(&p,s->accent);p16(&p,s->drive);p8(&p,s->square);const seq16_t*q=&g->acid_seq[a];for(unsigned i=0;i<16u;i++){p8(&p,q->step[i].note);p8(&p,q->step[i].flags);p8(&p,q->step[i].probability);p8(&p,(uint8_t)q->step[i].micro);}p32(&p,q->rng);}for(unsigned d=0;d<2u;d++)for(unsigned i=0;i<16u;i++){p16(&p,g->drum_hits[d][i]);p16(&p,g->drum_accents[d][i]);}for(unsigned i=0;i<MIX_TRACKS;i++){p16(&p,(uint16_t)g->mixer.track[i].level);p16(&p,(uint16_t)g->mixer.track[i].pan);p8(&p,g->mixer.track[i].mute);p8(&p,g->mixer.track[i].solo);p8(&p,g->mixer.track[i].delay_send);}p16(&p,(uint16_t)g->mixer.drive);p16(&p,(uint16_t)g->mixer.compressor_threshold);p16(&p,(uint16_t)g->mixer.filter_cutoff);p16(&p,g->mixer.delay_len);p16(&p,(uint16_t)g->mixer.delay_feedback);p16(&p,(uint16_t)g->mixer.delay_mix);p8(&p,g->song.length);p8(&p,g->song.loop);for(unsigned i=0;i<g->song.length;i++){p8(&p,g->song.slot[i].pattern);p8(&p,g->song.slot[i].repeats);}
/* Optional v1 extension: A-H bank snapshot. Current active pattern is serialized from live state. */p8(&p,0xA8u);p8(&p,1u);for(unsigned pat=0;pat<PATTERN_BANK_COUNT;pat++){for(unsigned a=0;a<2u;a++)for(unsigned i=0;i<16u;i++){const seq16_step_t*s=pat==g->current_pattern?&g->acid_seq[a].step[i]:&g->patterns.acid[a][pat][i];p8(&p,s->note);p8(&p,s->flags);p8(&p,s->probability);p8(&p,(uint8_t)s->micro);}for(unsigned d=0;d<2u;d++)for(unsigned i=0;i<16u;i++){uint16_t h=pat==g->current_pattern?g->drum_hits[d][i]:g->patterns.drum_hits[d][pat][i];uint16_t ac=pat==g->current_pattern?g->drum_accents[d][i]:g->patterns.drum_accents[d][pat][i];p16(&p,h);p16(&p,ac);}}
size_t n=(size_t)(p-b);if(n>sizeof(b))return PROJECT_ERR_LENGTH;return project_encode(out,cap,b,n,written);}

int groovebox_load(groovebox_t*g,const uint8_t*blob,size_t blob_len){uint8_t b[GROOVEBOX_PROJECT_PAYLOAD_MAX];size_t n=0;int rc=project_decode(blob,blob_len,b,sizeof(b),&n);if(rc!=PROJECT_OK)return rc;const uint8_t*p=b,*end=b+n;
#define NEED(k) do{if((size_t)(end-p)<(k))return PROJECT_ERR_LENGTH;}while(0)
NEED(4);uint16_t bpm=g16(&p);uint8_t pat=g8(&p),ext=g8(&p);if(pat>=PATTERN_BANK_COUNT)return PROJECT_ERR_LENGTH;groovebox_init(g,bpm);g->current_pattern=pat;g->external_clock=ext?1u:0u;for(unsigned a=0;a<2u;a++){NEED(13);acid303_t*s=&g->acid[a];s->cutoff=g16(&p);s->resonance=g16(&p);s->env_mod=g16(&p);s->decay=g16(&p);s->accent=g16(&p);s->drive=g16(&p);s->square=g8(&p);for(unsigned i=0;i<16u;i++){NEED(4);g->acid_seq[a].step[i].note=g8(&p);g->acid_seq[a].step[i].flags=g8(&p);g->acid_seq[a].step[i].probability=g8(&p);g->acid_seq[a].step[i].micro=(int8_t)g8(&p);}NEED(4);g->acid_seq[a].rng=g32(&p);}for(unsigned d=0;d<2u;d++)for(unsigned i=0;i<16u;i++){NEED(4);g->drum_hits[d][i]=g16(&p);g->drum_accents[d][i]=g16(&p);}for(unsigned i=0;i<MIX_TRACKS;i++){NEED(7);g->mixer.track[i].level=(int16_t)g16(&p);g->mixer.track[i].pan=(int16_t)g16(&p);g->mixer.track[i].mute=g8(&p);g->mixer.track[i].solo=g8(&p);g->mixer.track[i].delay_send=g8(&p);}NEED(12);g->mixer.drive=(int16_t)g16(&p);g->mixer.compressor_threshold=(int16_t)g16(&p);g->mixer.filter_cutoff=(int16_t)g16(&p);g->mixer.delay_len=g16(&p);g->mixer.delay_feedback=(int16_t)g16(&p);g->mixer.delay_mix=(int16_t)g16(&p);NEED(2);uint8_t sl=g8(&p),loop=g8(&p);if(sl>SONG_MAX_SLOTS)return PROJECT_ERR_LENGTH;g->song.length=sl;g->song.loop=loop?1u:0u;for(unsigned i=0;i<sl;i++){NEED(2);g->song.slot[i].pattern=g8(&p);g->song.slot[i].repeats=g8(&p);if(g->song.slot[i].pattern>=PATTERN_BANK_COUNT||!g->song.slot[i].repeats)return PROJECT_ERR_LENGTH;}
if(p==end){active_to_bank(&g->patterns,g,g->current_pattern);return PROJECT_OK;}NEED(2);if(g8(&p)!=0xA8u||g8(&p)!=1u)return PROJECT_ERR_VERSION;for(unsigned pp=0;pp<PATTERN_BANK_COUNT;pp++){for(unsigned a=0;a<2u;a++)for(unsigned i=0;i<16u;i++){NEED(4);seq16_step_t*s=&g->patterns.acid[a][pp][i];s->note=g8(&p);s->flags=g8(&p);s->probability=g8(&p);s->micro=(int8_t)g8(&p);}for(unsigned d=0;d<2u;d++)for(unsigned i=0;i<16u;i++){NEED(4);g->patterns.drum_hits[d][pp][i]=g16(&p);g->patterns.drum_accents[d][pp][i]=g16(&p);}}if(p!=end)return PROJECT_ERR_LENGTH;active_to_bank(&g->patterns,g,g->current_pattern);
#undef NEED
return PROJECT_OK;}
