#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate compact band-limited Q15 oscillator tables for the acid engine.

The layout is inspired by js303's useful idea of moving Fourier work out of the
audio callback, but uses generated C/Q15 data rather than a browser PNG. Ten
frequency bands cover the acid range; each band contains 512 samples for SAW
and a 65%-duty 303-style pulse. Harmonics are limited to 22.05 kHz so the same
tables are safe for the 44.1 kHz output path even though the ladder runs at 2x.
"""
from __future__ import annotations
import argparse, math
from pathlib import Path

BAND_NOTES = [24, 32, 40, 48, 56, 64, 72, 80, 88, 96]
SIZE = 512
OUT_SR = 44100.0
BANDLIMIT_HZ = OUT_SR * 0.5
DUTY = 0.65


def hz(note: int) -> float:
    return 440.0 * 2.0 ** ((note - 69) / 12.0)


def phase_inc(note: int) -> int:
    return round((2.0**32) * hz(note) / OUT_SR)


def wave(note: int, pulse: bool) -> tuple[list[int], int]:
    harmonics = max(1, int(BANDLIMIT_HZ // hz(note)))
    values: list[float] = []
    for n in range(SIZE):
        t = n / SIZE
        v = 0.0
        for k in range(1, harmonics + 1):
            if pulse:
                # Zero-mean Fourier pulse with the intentionally asymmetric
                # duty used by the fixed-point 303 square path.
                v += (2.0 / (math.pi * k)) * math.sin(math.pi * k * DUTY) * math.cos(
                    2.0 * math.pi * k * (t - DUTY / 2.0)
                )
            else:
                v += -2.0 / (math.pi * k) * math.sin(2.0 * math.pi * k * t)
        values.append(v)
    peak = max(abs(v) for v in values) or 1.0
    scale = 30000.0 / peak
    return [max(-32768, min(32767, round(v * scale))) for v in values], harmonics


def c_array(name: str, values: list[int]) -> str:
    rows = []
    for i in range(0, len(values), 12):
        rows.append("    " + ", ".join(str(v) for v in values[i : i + 12]) + ",")
    return f"static const int16_t {name}[REFM_ACID_WT_SIZE] = {{\n" + "\n".join(rows) + "\n};\n"


def generate() -> str:
    tables = []
    harmonic_counts = []
    for note in BAND_NOTES:
        saw, harmonics = wave(note, False)
        square, _ = wave(note, True)
        tables.append((saw, square))
        harmonic_counts.append(harmonics)
    mids = [(BAND_NOTES[i] + BAND_NOTES[i + 1]) // 2 for i in range(len(BAND_NOTES) - 1)]
    thresholds = [phase_inc(note) for note in mids]
    out = [
        "// SPDX-License-Identifier: GPL-3.0-only\n",
        "/* Generated by tools/generate_303_wavetables.py. Do not hand-edit. */\n",
        "#ifndef REFM_ACID303_WAVETABLE_H\n#define REFM_ACID303_WAVETABLE_H\n#include <stdint.h>\n",
        "#define REFM_ACID_WT_BANDS 10u\n#define REFM_ACID_WT_SIZE 512u\n#define REFM_ACID_WT_MASK 511u\n",
        "static const uint32_t refm_acid_wt_threshold_inc[REFM_ACID_WT_BANDS-1u] = {\n    "
        + ", ".join(f"{v}u" for v in thresholds)
        + "\n};\n",
        "static const uint16_t refm_acid_wt_harmonics[REFM_ACID_WT_BANDS] = {\n    "
        + ", ".join(str(v) for v in harmonic_counts)
        + "\n};\n",
    ]
    for i, (saw, square) in enumerate(tables):
        out.append(c_array(f"refm_acid_wt_saw_{i}", saw))
        out.append(c_array(f"refm_acid_wt_square_{i}", square))
    out.append(
        "static const int16_t *const refm_acid_wt_saw[REFM_ACID_WT_BANDS] = {\n    "
        + ", ".join(f"refm_acid_wt_saw_{i}" for i in range(len(tables)))
        + "\n};\n"
    )
    out.append(
        "static const int16_t *const refm_acid_wt_square[REFM_ACID_WT_BANDS] = {\n    "
        + ", ".join(f"refm_acid_wt_square_{i}" for i in range(len(tables)))
        + "\n};\n#endif\n"
    )
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", type=Path, default=Path("firmware/proto/acid303_wavetable.h"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = generate()
    if args.check:
        if not args.output.exists() or args.output.read_text() != text:
            raise SystemExit(f"wavetable is stale: run {Path(__file__).as_posix()}")
        print(f"303 wavetable ok: {len(BAND_NOTES)} bands x {SIZE} x 2 Q15")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {args.output}: {len(BAND_NOTES)} bands x {SIZE} x 2 Q15")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
