#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate browser-only Open303-style 2048x12 SAW303/SQUARE303 mipmaps.

The prototype construction and octave mip strategy mirror Open303's
MipMappedWaveTable. The emitted interface intentionally matches the compact
firmware wavetable header so the browser HQ core can switch tables without
changing the FM-1 implementation.
"""
from __future__ import annotations
import argparse, math
from pathlib import Path

N=2048
LEVELS=12
DRIVE_DB=36.9
OFFSET=4.37
PHASE_DEG=180.0


def fft(a:list[complex], inverse:bool=False)->list[complex]:
    n=len(a); out=list(a); j=0
    for i in range(1,n):
        bit=n>>1
        while j&bit:
            j^=bit; bit>>=1
        j^=bit
        if i<j: out[i],out[j]=out[j],out[i]
    length=2
    while length<=n:
        ang=(2.0*math.pi/length)*(1.0 if inverse else -1.0)
        wlen=complex(math.cos(ang),math.sin(ang)); half=length>>1
        for i in range(0,n,length):
            w=1+0j
            for k in range(half):
                u=out[i+k]; v=out[i+k+half]*w
                out[i+k]=u+v; out[i+k+half]=u-v; w*=wlen
        length<<=1
    if inverse: out=[x/n for x in out]
    return out


def saw303()->list[float]:
    n1=max(1,min(N-1,round(0.5*(N-1)))); n2=N-n1
    s1=1.0/(n1-1); s2=1.0/n2
    return [s1*i if i<n1 else -1.0+s2*(i-n1) for i in range(N)]


def square303(saw:list[float])->list[float]:
    factor=10.0**(DRIVE_DB/20.0)
    x=[-math.tanh(factor*v+OFFSET) for v in saw]
    shift=round(N*PHASE_DEG/360.0)%N
    return x[-shift:]+x[:-shift] if shift else x


def mipmaps(proto:list[float])->list[list[float]]:
    tables=[list(proto)]
    spec=fft([complex(v,0.0) for v in proto])
    spec[0]=0j; spec[N//2]=0j
    for t in range(1,LEVELS):
        low=N//(2**t); high=N//(2**(t-1))
        for k in range(low,high):
            spec[k]=0j
            if k: spec[N-k]=0j
        tables.append([z.real for z in fft(spec,True)])
    return tables


def q15(v:float)->int:
    return max(-32768,min(32767,round(v*32767.0)))


def emit_single(name:str,values:list[float])->str:
    vals=[q15(v) for v in values]; out=[f"static const int16_t {name}[REFM_ACID_WT_SIZE] = {{\n"]
    for i in range(0,N,16): out.append("    "+", ".join(map(str,vals[i:i+16]))+",\n")
    out.append("};\n"); return ''.join(out)


def generate()->str:
    saw=mipmaps(saw303()); sq=mipmaps(square303(saw303()))
    # Open303 selects tableNumber = exponent(2048*freq/176400) + 2.
    # acid303_hq.c measures pitch as a 44.1-kHz Q32 phase increment, so the
    # corresponding boundaries are powers of two beginning at 2^22.
    thresholds=[min(0xffffffff,1<<(22+i)) for i in range(LEVELS-1)]
    out=[
        "// SPDX-License-Identifier: GPL-3.0-only\n",
        "/* Generated by tools/generate_303_hq_wavetables.py. Do not hand-edit. */\n",
        "#ifndef REFM_ACID303_WAVETABLE_H\n#define REFM_ACID303_WAVETABLE_H\n#include <stdint.h>\n",
        f"#define REFM_ACID_WT_BANDS {LEVELS}u\n#define REFM_ACID_WT_BITS 11u\n#define REFM_ACID_WT_SIZE {N}u\n#define REFM_ACID_WT_MASK {N-1}u\n",
        "static const uint32_t refm_acid_wt_threshold_inc[REFM_ACID_WT_BANDS-1u] = {\n    "+", ".join(f"{x}u" for x in thresholds)+"\n};\n"
    ]
    for i in range(LEVELS):
        out.append(emit_single(f"refm_acid_wt_saw_{i}",saw[i]))
        out.append(emit_single(f"refm_acid_wt_square_{i}",sq[i]))
    out.append("static const int16_t *const refm_acid_wt_saw[REFM_ACID_WT_BANDS] = {\n    "+", ".join(f"refm_acid_wt_saw_{i}" for i in range(LEVELS))+"\n};\n")
    out.append("static const int16_t *const refm_acid_wt_square[REFM_ACID_WT_BANDS] = {\n    "+", ".join(f"refm_acid_wt_square_{i}" for i in range(LEVELS))+"\n};\n#endif\n")
    return ''.join(out)


def main()->int:
    ap=argparse.ArgumentParser(); ap.add_argument("--output",type=Path,default=Path("build/wasm/acid303_hq_wavetable.h")); ap.add_argument("--check",action="store_true"); args=ap.parse_args()
    text=generate()
    if args.check:
        if not args.output.exists() or args.output.read_text()!=text: raise SystemExit("HQ wavetable is stale")
        print(f"303 HQ wavetable ok: {LEVELS} x {N} x 2 Q15"); return 0
    args.output.parent.mkdir(parents=True,exist_ok=True); args.output.write_text(text); print(f"wrote {args.output}: {LEVELS} x {N} x 2 Q15"); return 0

if __name__=='__main__': raise SystemExit(main())
