#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate browser-only 2048x12 TB-303 reference mipmaps.

For the WASM reference path we deliberately use the spectral construction from
js303 as a second benchmark beside Open303: all harmonics for saw, odd
harmonics only for square, with a cosine-squared roll-off toward the highest
retained partial.  This produces a stable hollow/reedy square without the
experimental pulse-width/memory model that drifted away from the reference.

The emitted interface matches the compact firmware wavetable header so the
FM-1 implementation remains untouched.
"""
from __future__ import annotations
import argparse, math
from pathlib import Path

N=2048
LEVELS=12


def normalize_bank(tables:list[list[float]])->list[list[float]]:
    peak=max(max(abs(v) for v in table) for table in tables)
    if peak <= 0.0:
        raise RuntimeError("wavetable bank is silent")
    scale=1.0/peak
    return [[v*scale for v in table] for table in tables]


def spectral_table(hmax:int, odd_only:bool)->list[float]:
    """Render one js303-style band-limited waveform.

    js303 weights harmonic j with
      cos^2((j-1) * pi / (2*hmax)) / j
    and keeps only odd j for square.  We retain that spectral shape while using
    our 2048-sample mipmapped representation instead of js303's per-MIDI-note
    4096-sample table bank.
    """
    h=max(1,min(N//2-1,hmax))
    out=[0.0]*N
    for j in range(1,h+1):
        if odd_only and not (j&1):
            continue
        taper=math.cos((j-1)*0.5*math.pi/h)
        amp=(taper*taper)/j
        for k in range(N):
            out[k]+=amp*math.sin(2.0*math.pi*j*k/N)
    return out


def js303_mips(odd_only:bool)->list[list[float]]:
    tables=[]
    for level in range(LEVELS):
        # Each successive mip retains roughly half the harmonics, matching the
        # octave-spaced selection used by the HQ oscillator.
        hmax=max(1,(N//2-1)//(1<<level))
        tables.append(spectral_table(hmax,odd_only))
    return normalize_bank(tables)


def validate_mips(name:str,tables:list[list[float]])->None:
    for i,table in enumerate(tables):
        peak=max(abs(v) for v in table)
        rms=math.sqrt(sum(v*v for v in table)/len(table))
        if peak < 1e-5 or rms < 1e-6:
            raise RuntimeError(f"{name} mip {i} is effectively silent: peak={peak} rms={rms}")


def q15(v:float)->int:
    return max(-32768,min(32767,round(v*32767.0)))


def emit_single(name:str,values:list[float])->str:
    vals=[q15(v) for v in values]
    out=[f"static const int16_t {name}[REFM_ACID_WT_SIZE] = {{\n"]
    for i in range(0,N,16):
        out.append("    "+", ".join(map(str,vals[i:i+16]))+",\n")
    out.append("};\n")
    return ''.join(out)


def generate()->str:
    saw=js303_mips(False)
    square=js303_mips(True)
    validate_mips("SAW",saw)
    validate_mips("SQUARE",square)

    # The HQ oscillator runs at 4x but represents pitch using the 44.1-kHz Q32
    # phase increment. These octave thresholds retain the existing proven mip
    # selection and avoid the high-note silence regression.
    thresholds=[min(0xffffffff,1<<(22+i)) for i in range(LEVELS-1)]
    out=[
        "// SPDX-License-Identifier: GPL-3.0-only\n",
        "/* Generated by tools/generate_303_hq_wavetables.py. Do not hand-edit. */\n",
        "#ifndef REFM_ACID303_WAVETABLE_H\n#define REFM_ACID303_WAVETABLE_H\n#include <stdint.h>\n",
        f"#define REFM_ACID_WT_BANDS {LEVELS}u\n#define REFM_ACID_WT_BITS 11u\n#define REFM_ACID_WT_SIZE {N}u\n#define REFM_ACID_WT_MASK {N-1}u\n",
        "static const uint32_t refm_acid_wt_threshold_inc[REFM_ACID_WT_BANDS-1u] = {\n    "+", ".join(f"{x}u" for x in thresholds)+"\n};\n"
    ]
    for i in range(LEVELS):
        out.append(emit_single(f"refm_acid_wt_saw_{i}",saw[i]))
        out.append(emit_single(f"refm_acid_wt_square_{i}",square[i]))
    out.append("static const int16_t *const refm_acid_wt_saw[REFM_ACID_WT_BANDS] = {\n    "+", ".join(f"refm_acid_wt_saw_{i}" for i in range(LEVELS))+"\n};\n")
    out.append("static const int16_t *const refm_acid_wt_square[REFM_ACID_WT_BANDS] = {\n    "+", ".join(f"refm_acid_wt_square_{i}" for i in range(LEVELS))+"\n};\n#endif\n")
    return ''.join(out)


def main()->int:
    ap=argparse.ArgumentParser()
    ap.add_argument("--output",type=Path,default=Path("build/wasm/acid303_hq_wavetable.h"))
    ap.add_argument("--check",action="store_true")
    args=ap.parse_args()
    text=generate()
    if args.check:
        if not args.output.exists() or args.output.read_text()!=text:
            raise SystemExit("HQ wavetable is stale")
        print(f"303 HQ wavetable ok: {LEVELS} x {N} x 2 Q15 (js303 spectral reference)")
        return 0
    args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {args.output}: {LEVELS} x {N} x 2 Q15")
    return 0

if __name__=='__main__':
    raise SystemExit(main())
